# Generated by Django 3.1.2 on 2020-12-12 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signupapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boeun_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='이름')),
                ('address', models.TextField(blank=True, verbose_name='주소')),
                ('contact', models.TextField(blank=True, verbose_name='연락처')),
                ('relation', models.TextField(blank=True, verbose_name='관계')),
                ('date_of_birth', models.TextField(blank=True, verbose_name='생년월일')),
                ('anniversary', models.TextField(blank=True, verbose_name='기념일')),
                ('health', models.TextField(blank=True, verbose_name='건강상태')),
                ('etc', models.TextField(blank=True, verbose_name='기타사항')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성날짜')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='수정날짜')),
            ],
        ),
    ]
