<<<<<<< HEAD
# Generated by Django 3.1.2 on 2020-11-16 13:18
=======
# Generated by Django 3.1.2 on 2020-11-16 20:11
>>>>>>> 8c6cd0723260e27df5ce0510d8f47c66c1ac24d4

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signupapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='student_id',
        ),
    ]
