# Generated by Django 3.1.2 on 2020-12-12 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signupapp', '0003_auto_20201212_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='boeun_user',
            name='family',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='family', to=settings.AUTH_USER_MODEL),
        ),
    ]
