# Generated by Django 3.1.2 on 2020-11-16 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cscenterapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FAQform',
            new_name='FAQ',
        ),
    ]
