# Generated by Django 3.1.2 on 2020-12-16 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signupapp', '0004_boeun_user_family'),
        ('cscenterapp', '0004_auto_20201203_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='qna',
            name='writer',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='signupapp.boeun_user'),
        ),
        migrations.AlterField(
            model_name='qna',
            name='desc',
            field=models.TextField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='qna',
            name='pic',
            field=models.ImageField(blank=True, upload_to='', verbose_name='사진 첨부'),
        ),
        migrations.AlterField(
            model_name='qna',
            name='title',
            field=models.CharField(max_length=200, verbose_name=''),
        ),
    ]
